cache:
  redis:
    host: "localhost:6379"
    password: changeme
  message: 
    ttl_in_minutes: 5


db:
  postgresql:
    dsn: "host=localhost user=gorm password=gorm dbname=gorm port=5432 sslmode=disable TimeZone=Asia/Shanghai"

process:
  task:
    count: 2
    # checks every minute
    cron: "0 * * * * *" 
    # should n minute past last processing time
    delta_in_minutes: 2 
    # retry 2 times at most
    retry: 2 

    message:
      max_content_length: 40
      url: https://webhook.site/smth
      auth:
        key: INS.smth