definitions:
  dto.MessageTaskCreateRequest:
    properties:
      content:
        type: string
      to:
        type: string
    type: object
  dto.MessageTaskCreateResponse:
    properties:
      id:
        type: integer
      message:
        type: string
    type: object
  dto.PageResponse-model_MessageTask:
    properties:
      data:
        items:
          $ref: '#/definitions/model.MessageTask'
        type: array
      page:
        type: integer
      pageSize:
        type: integer
    type: object
  dto.TaskStateUpdateRequest:
    properties:
      active:
        type: boolean
    type: object
  dto.TaskStateUpdateResponse:
    properties:
      active:
        type: boolean
      message:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.MessageTask:
    properties:
      content:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      status:
        $ref: '#/definitions/model.TaskStatus'
      to:
        type: string
      updatedAt:
        type: string
    type: object
  model.MessageTaskResult:
    properties:
      messageId:
        type: string
      sendingTime:
        type: string
      taskId:
        type: string
    type: object
  model.TaskStatus:
    enum:
    - WAITING
    - PROCESSING
    - COMPLETED
    - FAILED
    type: string
    x-enum-varnames:
    - WAITING
    - PROCESSING
    - COMPLETED
    - FAILED
info:
  contact: {}
paths:
  /api/v1/tasks:
    put:
      consumes:
      - application/json
      description: Creates new message task that will be consumed.
      parameters:
      - description: Add TaskStateUpdateRequest
        in: body
        name: TaskStateUpdateRequest
        required: true
        schema:
          $ref: '#/definitions/dto.TaskStateUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TaskStateUpdateResponse'
      summary: Updates Task State
      tags:
      - Task State
  /api/v1/tasks/messages:
    get:
      consumes:
      - application/json
      description: Gets message tasks with pagination
      parameters:
      - description: status filter
        enum:
        - COMPLETED
        - WAITING
        - PROCESSING
        - FAILED
        in: query
        name: status
        required: true
        type: string
      - description: page
        in: query
        minimum: 1
        name: page
        required: true
        type: number
      - description: page size
        in: query
        maximum: 20
        minimum: 1
        name: page_size
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PageResponse-model_MessageTask'
      summary: Gets message tasks with pagination
      tags:
      - Message Task
  /api/v1/tasks/messages/:
    post:
      consumes:
      - application/json
      description: Creates new message task that will be consumed.
      parameters:
      - description: MessageTaskCreateRequest
        in: body
        name: MessageTaskCreateRequest
        required: true
        schema:
          $ref: '#/definitions/dto.MessageTaskCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.MessageTaskCreateResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: CreatesMessageTask
      tags:
      - Message Task
  /api/v1/tasks/messages/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes message task that will
      parameters:
      - description: message task id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Deletes Message Task
      tags:
      - Message Task
    get:
      consumes:
      - application/json
      description: Gets message task result from cache
      parameters:
      - description: message id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MessageTaskResult'
      summary: Gets message task result from cache
      tags:
      - Message Task
  /health:
    get:
      consumes:
      - application/json
      description: response ok
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: health
      tags:
      - health
swagger: "2.0"
