version: '3.9'

services:
  redis:
    image: 'bitnami/redis:latest'
    env_file: "local.redis.env"
  
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: "local.postgresql.env"
      
